#ifndef PQCLEAN_NAMESPACE_API_H
#define PQCLEAN_NAMESPACE_API_H

#if   (KYBER_K == 2)
#define PQCLEAN_NAMESPACE_CRYPTO_SECRETKEYBYTES  1632
#define PQCLEAN_NAMESPACE_CRYPTO_PUBLICKEYBYTES  800
#define PQCLEAN_NAMESPACE_CRYPTO_CIPHERTEXTBYTES 736
#define PQCLEAN_NAMESPACE_CRYPTO_BYTES           32
#define PQCLEAN_NAMESPACE_CRYPTO_ALGNAME "Kyber512"
#elif (KYBER_K == 3)
#define PQCLEAN_NAMESPACE_CRYPTO_SECRETKEYBYTES  2400
#define PQCLEAN_NAMESPACE_CRYPTO_PUBLICKEYBYTES  1184
#define PQCLEAN_NAMESPACE_CRYPTO_CIPHERTEXTBYTES 1088
#define PQCLEAN_NAMESPACE_CRYPTO_BYTES           32
#define PQCLEAN_NAMESPACE_CRYPTO_ALGNAME "Kyber768"
#elif (KYBER_K == 4)
#define PQCLEAN_NAMESPACE_CRYPTO_SECRETKEYBYTES  3168
#define PQCLEAN_NAMESPACE_CRYPTO_PUBLICKEYBYTES  1568
#define PQCLEAN_NAMESPACE_CRYPTO_CIPHERTEXTBYTES 1568
#define PQCLEAN_NAMESPACE_CRYPTO_BYTES           32
#define PQCLEAN_NAMESPACE_CRYPTO_ALGNAME "Kyber1024"
#else
#error "KYBER_K must be in {2,3,4}"
#endif

int PQCLEAN_NAMESPACE_crypto_kem_keypair(unsigned char *pk, unsigned char *sk);

int PQCLEAN_NAMESPACE_crypto_kem_enc(unsigned char *ct, unsigned char *ss, const unsigned char *pk);

int PQCLEAN_NAMESPACE_crypto_kem_dec(unsigned char *ss, const unsigned char *ct, const unsigned char *sk);


#endif
