#ifndef PARAMS_H
#define PARAMS_H

#define KYBER_K 3
#define KYBER_N 256
#define KYBER_Q 7681


#if (KYBER_K == 2)   /* KYBER512 */
#define KYBER_ETA 5
#elif (KYBER_K == 4) /*KYBER1024 */
#define KYBER_ETA 3
#else                /*KYBER768 */
#define KYBER_ETA 4
#endif

#define KYBER_SEEDBYTES       32
#define KYBER_NOISESEEDBYTES  32
#define KYBER_COINBYTES       32
#define KYBER_SHAREDKEYBYTES  32

#define KYBER_POLYBYTES              416 
#define KYBER_POLYCOMPRESSEDBYTES    96 
#define KYBER_POLYVECBYTES           (KYBER_K * KYBER_POLYBYTES)   
#define KYBER_POLYVECCOMPRESSEDBYTES (KYBER_K * 352) 

#define KYBER_INDCPA_MSGBYTES       32
#define KYBER_INDCPA_PUBLICKEYBYTES (KYBER_POLYVECCOMPRESSEDBYTES + KYBER_SEEDBYTES)
#define KYBER_INDCPA_SECRETKEYBYTES (KYBER_POLYVECBYTES)
#define KYBER_INDCPA_BYTES          (KYBER_POLYVECCOMPRESSEDBYTES + KYBER_POLYCOMPRESSEDBYTES)

#define KYBER_PUBLICKEYBYTES  (KYBER_INDCPA_PUBLICKEYBYTES)
#define KYBER_SECRETKEYBYTES  (KYBER_INDCPA_SECRETKEYBYTES +  KYBER_INDCPA_PUBLICKEYBYTES + 32 + KYBER_SHAREDKEYBYTES)
#define KYBER_CIPHERTEXTBYTES (KYBER_INDCPA_BYTES+KYBER_INDCPA_MSGBYTES) /* Second part is for Targhi-Unruh */

#endif
